Fixes for Local- and RemoteObjectRepo
hpi-swa-teaching/Liquid pull request #103
Opened 2021-07-01 14:13 UTC by NikkelM

The LocalObjectRepo had a bug where it needed its `ifPresent:`-Block to have 0 arguments, but it got 1 instead (RemoteObjectRepo needs the exact opposite!). 
The RemoteRepoClient was checking if `resp status = 409`, when it should have checked if `resp code = 409`.

2021-07-01 14:42 UTC, Skn0tt approved these changes

2021-07-01 20:05 UTC, Dassderdie approved these changes
LGTM

2021-07-02 11:17 UTC, NikkelM commented
Due to a faulty merge of main into this branch, the PR has been re-instantiated as PR #106

2021-07-02 11:17 UTC, closed without merging

2021-07-03 10:36 UTC, PaulVII requested changes
Der PR zerstört die gesamte CI, alle Änderungen an Ci-spezifischen Dateien müssen rückgängig gemacht werden. Sonst sieht das gut aus :)

2021-07-03 10:36 UTC, PaulVII commented on scripts/preLoading.st
> -Scanner allowBlockArgumentAssignment: true.
Mountain: darf nicht gelöscht werden. Ebenso die ganzen Änderungen an anderen lint-bezogenen dateien

2021-07-03 10:39 UTC, NikkelM commented on scripts/preLoading.st
> -Scanner allowBlockArgumentAssignment: true.
Diesen Branch hatte ich eigentlich schon gelöscht bzw. den PR geschlossen, eben wegen diesen Fehlern, die kamen irgendwann beim merge von main dazu. Aktueller PR ist #106, da läuft die CI auch durch ;)