added run poll UI-feedback
hpi-swa-teaching/Liquid pull request #116
Opened 2021-07-09 12:33 UTC by Dassderdie

2021-07-15 12:49 UTC, Dassderdie commented
@Skn0tt This branch is now ready for your review ;)

2021-07-16 09:42 UTC, Skn0tt requested changes

2021-07-16 09:42 UTC, Skn0tt commented on packages/Liquid-Core.package/LiquidPollDraftBuilder.class/instance/runPoll.st
> +		ifTaken: [UIManager default inform: 'This ID is already taken'. taken:= true].
```suggestion
		ifTaken: [^ UIManager default inform: 'This ID is already taken'. taken:= true].
```

allows removing taken

2021-07-16 09:42 UTC, Skn0tt commented on packages/Liquid-Core.package/LiquidRunningPollView.class/instance/getID.st
> +getID
[dust] maybe `pollId` instead

2021-07-16 11:13 UTC, Skn0tt approved these changes

2021-07-16 11:13 UTC, merged